version: '3.1'
 
services:
  jenkins:
    build: .
    image: apigee-ci 
    ports: 
      - "8080:8080"
    secrets:
      - apigee-organization
      - apigee-username
      - apigee-password
      - git-private-key
 
secrets:
  apigee-organization:
    file: ./secrets/apigee-organization
  apigee-username:
    file: ./secrets/apigee-username
  apigee-password:
    file: ./secrets/apigee-password
  git-private-key:
    file: ./secrets/git-private-key
    
