version: '3.1'
 
services:
  jenkins:
    build: .
    image: apigee-ci 
    ports: 
      - "8080:8080"
    secrets:
      - apigee-credentials
      - git-private-key
secrets:
  apigee-credentials:
    file: ./secrets/apigee-credentials
  git-private-key:
    file: ./secrets/git-private-key
    
